### PR TITLE
Xcode 6.3 support

### PR DESCRIPTION
**Pull request by glentregoning**
- Support Swift 1.2 syntax
- Fixing test warnings

### CODE REVIEW

**Comment by glentregoning** [comment]
Issue tracked by  #85

**Comment by MosheBerman** [comment]
Xcode 8 is on its way, so I'm assuming this isn't necessary anymore?

**Comment by glentregoning** [comment]
So I'm not using this pod anymore, but I suspect you'd want these fixed in addition to others for Xcode8.

**Comment by MosheBerman** [comment]
Ok, thanks. Just curious what you're using now, if anything, and what I might do to make CalendarKit more useful to you?

**Comment by glentregoning** [comment]
Sure I'm using JTCalendar as it's more modular.

**Pull request closed without merging**
